import type { MigrationInterface, QueryRunner } from 'typeorm';

export class Wave4MasterData1710000018000 implements MigrationInterface {
  name = 'Wave4MasterData1710000018000';
  async up(q: QueryRunner): Promise<void> {
    await q.query('CREATE EXTENSION IF NOT EXISTS btree_gist');
    await q.query(`CREATE TABLE safety_equipment_categories (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code VARCHAR(64) NOT NULL, name VARCHAR(128) NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'active', created_by VARCHAR(64) NOT NULL, updated_by VARCHAR(64), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), deleted_at TIMESTAMPTZ)`);
    await q.query(`CREATE UNIQUE INDEX uq_safety_equipment_categories_code ON safety_equipment_categories(code) WHERE deleted_at IS NULL`);
    await q.query(`CREATE TRIGGER set_safety_equipment_categories_updated_at BEFORE UPDATE ON safety_equipment_categories FOR EACH ROW EXECUTE FUNCTION set_updated_at()`);
    await q.query(`CREATE TABLE safety_equipment (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code VARCHAR(64) NOT NULL, name VARCHAR(128) NOT NULL, category_id UUID NOT NULL REFERENCES safety_equipment_categories(id) ON DELETE RESTRICT, vessel_id UUID NOT NULL REFERENCES vessels(id) ON DELETE RESTRICT, serial_no VARCHAR(128), status VARCHAR(16) NOT NULL DEFAULT 'active', remarks TEXT, created_by VARCHAR(64) NOT NULL, updated_by VARCHAR(64), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), deleted_at TIMESTAMPTZ, CONSTRAINT ck_safety_equipment_status CHECK (status IN ('active','inactive','retired')))`);
    await q.query(`CREATE UNIQUE INDEX uq_safety_equipment_code ON safety_equipment(code) WHERE deleted_at IS NULL`);
    await q.query(`CREATE INDEX idx_safety_equipment_vessel_status ON safety_equipment(vessel_id,status) WHERE deleted_at IS NULL`);
    await q.query(`CREATE TRIGGER set_safety_equipment_updated_at BEFORE UPDATE ON safety_equipment FOR EACH ROW EXECUTE FUNCTION set_updated_at()`);
    await q.query(`CREATE TABLE vessel_personnel_assignments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), vessel_id UUID NOT NULL REFERENCES vessels(id) ON DELETE RESTRICT, personnel_id UUID NOT NULL REFERENCES personnel(id) ON DELETE RESTRICT, role_code VARCHAR(64) NOT NULL, effective_from DATE NOT NULL, effective_to DATE, status VARCHAR(16) NOT NULL DEFAULT 'active', vessel_name_snapshot VARCHAR(128) NOT NULL, personnel_name_snapshot VARCHAR(128) NOT NULL, created_by VARCHAR(64) NOT NULL, updated_by VARCHAR(64), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), deleted_at TIMESTAMPTZ, CONSTRAINT ck_vessel_personnel_assignment_dates CHECK (effective_to IS NULL OR effective_to > effective_from), CONSTRAINT ck_vessel_personnel_assignment_status CHECK (status IN ('active','ended')))`);
    await q.query(`CREATE INDEX idx_vessel_personnel_assignments_personnel_effective ON vessel_personnel_assignments(personnel_id,effective_from) WHERE deleted_at IS NULL`);
    await q.query(`CREATE INDEX idx_vessel_personnel_assignments_vessel_status ON vessel_personnel_assignments(vessel_id,status) WHERE deleted_at IS NULL`);
    await q.query(`ALTER TABLE vessel_personnel_assignments ADD CONSTRAINT ex_vessel_personnel_assignments_personnel_period EXCLUDE USING gist (personnel_id WITH =, daterange(effective_from, COALESCE(effective_to, 'infinity'::date), '[]') WITH &&) WHERE (status = 'active' AND deleted_at IS NULL)`);
    await q.query(`CREATE TRIGGER set_vessel_personnel_assignments_updated_at BEFORE UPDATE ON vessel_personnel_assignments FOR EACH ROW EXECUTE FUNCTION set_updated_at()`);
    await q.query(`CREATE TABLE master_data_import_batches (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), import_type VARCHAR(32) NOT NULL, content_hash VARCHAR(64) NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'completed', summary JSONB NOT NULL DEFAULT '{}'::jsonb, created_by VARCHAR(64) NOT NULL, updated_by VARCHAR(64), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), deleted_at TIMESTAMPTZ, CONSTRAINT ck_master_data_import_batches_status CHECK (status IN ('running','completed','failed')))`);
    await q.query(`CREATE UNIQUE INDEX uq_master_data_import_batches_type_hash ON master_data_import_batches(import_type,content_hash) WHERE deleted_at IS NULL`);
    await q.query(`CREATE TRIGGER set_master_data_import_batches_updated_at BEFORE UPDATE ON master_data_import_batches FOR EACH ROW EXECUTE FUNCTION set_updated_at()`);
    await q.query(`CREATE TABLE master_data_import_rows (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), batch_id UUID NOT NULL REFERENCES master_data_import_batches(id) ON DELETE RESTRICT, row_no INTEGER NOT NULL, natural_key VARCHAR(256), outcome VARCHAR(16) NOT NULL, error_code VARCHAR(64), error_message TEXT, before_snapshot JSONB, created_by VARCHAR(64) NOT NULL, updated_by VARCHAR(64), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), deleted_at TIMESTAMPTZ, CONSTRAINT ck_master_data_import_rows_outcome CHECK (outcome IN ('created','updated','skipped','failed')))`);
    await q.query(`CREATE UNIQUE INDEX uq_master_data_import_rows_batch_row ON master_data_import_rows(batch_id,row_no) WHERE deleted_at IS NULL`);
    await q.query(`CREATE TRIGGER set_master_data_import_rows_updated_at BEFORE UPDATE ON master_data_import_rows FOR EACH ROW EXECUTE FUNCTION set_updated_at()`);
    await q.query(`CREATE TABLE workbench_master_data_references (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), source_domain VARCHAR(64) NOT NULL, source_record_id UUID NOT NULL REFERENCES workbench_records(id) ON DELETE RESTRICT, field_key VARCHAR(128) NOT NULL, object_type VARCHAR(32) NOT NULL, raw_value TEXT NOT NULL, object_id UUID, display_snapshot VARCHAR(256), mapping_status VARCHAR(32) NOT NULL, created_by VARCHAR(64) NOT NULL, updated_by VARCHAR(64), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), deleted_at TIMESTAMPTZ, CONSTRAINT ck_workbench_master_data_references_type CHECK (object_type IN ('vessel','personnel','equipment')), CONSTRAINT ck_workbench_master_data_references_status CHECK (mapping_status IN ('matched','ambiguous','unmatched','manual_override')))`);
    await q.query(`CREATE UNIQUE INDEX uq_workbench_master_data_reference_source ON workbench_master_data_references(source_domain,source_record_id,field_key,object_type) WHERE deleted_at IS NULL`);
    await q.query(`CREATE INDEX idx_workbench_master_data_reference_object ON workbench_master_data_references(object_type,object_id) WHERE deleted_at IS NULL`);
    await q.query(`CREATE TRIGGER set_workbench_master_data_references_updated_at BEFORE UPDATE ON workbench_master_data_references FOR EACH ROW EXECUTE FUNCTION set_updated_at()`);
  }
  async down(q: QueryRunner): Promise<void> {
    const equipmentCertificates = await q.query(`SELECT count(*)::int AS count FROM certificates WHERE owner_type = 'equipment' AND deleted_at IS NULL`) as Array<{ count: number }>;
    if (Number(equipmentCertificates[0]?.count ?? 0) > 0) throw new Error('cannot roll back Wave 4 while equipment certificates exist');
    await q.query('DROP TRIGGER IF EXISTS set_workbench_master_data_references_updated_at ON workbench_master_data_references'); await q.query('DROP TABLE IF EXISTS workbench_master_data_references');
    await q.query('DROP TRIGGER IF EXISTS set_master_data_import_rows_updated_at ON master_data_import_rows'); await q.query('DROP TABLE IF EXISTS master_data_import_rows');
    await q.query('DROP TRIGGER IF EXISTS set_master_data_import_batches_updated_at ON master_data_import_batches'); await q.query('DROP TABLE IF EXISTS master_data_import_batches');
    await q.query('DROP TRIGGER IF EXISTS set_vessel_personnel_assignments_updated_at ON vessel_personnel_assignments'); await q.query('DROP TABLE IF EXISTS vessel_personnel_assignments');
    await q.query('DROP TRIGGER IF EXISTS set_safety_equipment_updated_at ON safety_equipment'); await q.query('DROP TABLE IF EXISTS safety_equipment');
    await q.query('DROP TRIGGER IF EXISTS set_safety_equipment_categories_updated_at ON safety_equipment_categories'); await q.query('DROP TABLE IF EXISTS safety_equipment_categories');
  }
}
