#!/usr/bin/env python3
"""Refresh Enterprise WeCom callback IP allowlists for Sunan deployment."""

from __future__ import annotations

import ipaddress
import json
import os
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable
from urllib.parse import urlencode
from urllib.request import urlopen


ENV_FILE = Path(os.environ.get("SUNAN_ENV_FILE", "/dev/sunan/deploy/.env"))
OUTPUT_DIR = Path(os.environ.get("SUNAN_WECOM_IP_DIR", "/dev/sunan/sunan-wecom-ips"))
CALLBACK_LIST = OUTPUT_DIR / "callback-ip-list.txt"
CALLBACK_AUTO_LIST = OUTPUT_DIR / "callback-ip-list.auto.txt"
API_DOMAIN_LIST = OUTPUT_DIR / "api-domain-ip-list.txt"
NGINX_ALLOW_CONF = OUTPUT_DIR / "callback-allow.conf"
STATE_FILE = OUTPUT_DIR / "state.json"
QYAPI_BASE_URL = "https://qyapi.weixin.qq.com"


def main() -> int:
    env = read_env(ENV_FILE)
    access_token = get_access_token(env["WECOM_CORP_ID"], env["WECOM_AGENT_SECRET"])
    callback_ips = get_ip_list("/cgi-bin/getcallbackip", access_token)
    api_domain_ips = get_ip_list("/cgi-bin/get_api_domain_ip", access_token)
    manual_ips = parse_manual_ranges(env.get("WECOM_CALLBACK_ALLOWED_IP_RANGES", ""))
    combined_callback_ips = unique([*callback_ips, *manual_ips])

    if not callback_ips:
        raise RuntimeError("Enterprise WeCom returned an empty callback IP list")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    atomic_write(CALLBACK_AUTO_LIST, "\n".join(callback_ips) + "\n")
    atomic_write(CALLBACK_LIST, "\n".join(combined_callback_ips) + "\n")
    atomic_write(API_DOMAIN_LIST, "\n".join(api_domain_ips) + "\n")
    atomic_write(NGINX_ALLOW_CONF, render_nginx_allow_conf(combined_callback_ips))
    atomic_write(
        STATE_FILE,
        json.dumps(
            {
                "updatedAt": datetime.now(timezone.utc).isoformat(),
                "callbackIpCount": len(callback_ips),
                "manualIpCount": len(manual_ips),
                "combinedCallbackIpCount": len(combined_callback_ips),
                "apiDomainIpCount": len(api_domain_ips),
                "sources": {
                    "apiDomainIpDocument": "https://developer.work.weixin.qq.com/document/path/92520",
                    "callbackIpDocument": "https://developer.work.weixin.qq.com/document/path/92521",
                },
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
    )

    reload_nginx_if_running()
    print(
        f"updated callback_ips={len(callback_ips)} manual_ips={len(manual_ips)} "
        f"combined={len(combined_callback_ips)} api_domain_ips={len(api_domain_ips)}"
    )
    return 0


def read_env(path: Path) -> dict[str, str]:
    env: dict[str, str] = {}
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        env[key] = value
    for key in ("WECOM_CORP_ID", "WECOM_AGENT_SECRET"):
        if not env.get(key):
            raise RuntimeError(f"missing {key} in {path}")
    return env


def get_access_token(corp_id: str, corp_secret: str) -> str:
    payload = get_json(
        "/cgi-bin/gettoken",
        {"corpid": corp_id, "corpsecret": corp_secret},
    )
    token = payload.get("access_token")
    if payload.get("errcode") != 0 or not token:
        raise RuntimeError(f"gettoken failed: {payload}")
    return str(token)


def get_ip_list(path: str, access_token: str) -> list[str]:
    payload = get_json(path, {"access_token": access_token})
    raw_items = payload.get("ip_list")
    if payload.get("errcode") != 0 or not isinstance(raw_items, list):
        raise RuntimeError(f"{path} failed: {payload}")
    return unique(normalize_ip_range(str(item)) for item in raw_items)


def get_json(path: str, params: dict[str, str]) -> dict[str, object]:
    url = f"{QYAPI_BASE_URL}{path}?{urlencode(params)}"
    with urlopen(url, timeout=30) as response:
        return json.loads(response.read().decode("utf-8"))


def parse_manual_ranges(value: str) -> list[str]:
    raw_items = value.replace("\n", ",").split(",")
    return unique(normalize_ip_range(item) for item in raw_items if item.strip())


def normalize_ip_range(value: str) -> str:
    trimmed = value.strip()
    if "/" in trimmed:
        return str(ipaddress.ip_network(trimmed, strict=False))
    return str(ipaddress.ip_address(trimmed))


def unique(items: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    output: list[str] = []
    for item in items:
        if item and item not in seen:
            output.append(item)
            seen.add(item)
    return output


def render_nginx_allow_conf(items: list[str]) -> str:
    lines = [
        "# Generated by sunan-update-wecom-callback-ips.py; do not edit manually.",
        "# Enterprise WeCom callback IP ranges plus manual WECOM_CALLBACK_ALLOWED_IP_RANGES.",
    ]
    lines.extend(f"allow {item};" for item in items)
    return "\n".join(lines) + "\n"


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as tmp:
        tmp.write(content)
        tmp_path = Path(tmp.name)
    tmp_path.replace(path)


def reload_nginx_if_running() -> None:
    ps = subprocess.run(
        ["docker", "ps", "--format", "{{.Names}}"],
        check=False,
        text=True,
        capture_output=True,
    )
    if ps.returncode != 0 or "sunan-nginx" not in ps.stdout.splitlines():
        return
    include_exists = subprocess.run(
        ["docker", "exec", "sunan-nginx", "test", "-f", "/etc/nginx/wecom/callback-allow.conf"],
        check=False,
        text=True,
        capture_output=True,
    )
    if include_exists.returncode != 0:
        return
    subprocess.run(["docker", "exec", "sunan-nginx", "nginx", "-t"], check=True)
    subprocess.run(["docker", "exec", "sunan-nginx", "nginx", "-s", "reload"], check=True)


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"failed to update Enterprise WeCom callback IP allowlist: {exc}", file=sys.stderr)
        raise SystemExit(1)
